`define DBUS_OP_WIDTH 		2	
`define DBUS_ADDR_WIDTH 	5
`define DBUS_DATA_WIDTH 	34
`define DBUS_M_WIDTH 		`DBUS_OP_WIDTH + `DBUS_ADDR_WIDTH + `DBUS_DATA_WIDTH
`define DBUS_S_WIDTH 		`DBUS_OP_WIDTH + `DBUS_DATA_WIDTH	
`define IR_WIDTH		5
`define DBUS_M_WIDTH_MINUS_32 	`DBUS_M_WIDTH - 32
`define DBUS_M_WIDTH_MINUS_1 	`DBUS_M_WIDTH - 1
